import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { format } from 'date-fns';

interface ExportMetadata {
    user_name: string;
    user_role: string;
    store_name?: string;
    date_range?: string;
}

export const exportToPDF = (
    title: string,
    columns: string[],
    rows: any[][],
    metadata: ExportMetadata
) => {
    const doc = new jsPDF();

    // -- Header --
    doc.setFontSize(18);
    doc.text(title, 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by: ${metadata.user_name} (${metadata.user_role})`, 14, 28);
    doc.text(`Date: ${format(new Date(), 'dd MMM yyyy HH:mm')}`, 14, 33);
    if (metadata.store_name) {
        doc.text(`Store: ${metadata.store_name}`, 14, 38);
    }
    if (metadata.date_range) {
        doc.text(`Period: ${metadata.date_range}`, 14, 43);
    }

    // -- Watermark --
    doc.setTextColor(200, 200, 200);
    doc.setFontSize(40);
    doc.text('CONFIDENTIAL', 40, 150, { angle: 45 });
    if (metadata.user_role === 'auditor') {
        doc.text('AUDITOR COPY', 40, 180, { angle: 45 });
    }

    // -- Table --
    autoTable(doc, {
        startY: 50,
        head: [columns],
        body: rows,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185] },
        styles: { fontSize: 8 },
        didDrawPage: (data) => {
            // Footer
            doc.setFontSize(8);
            doc.setTextColor(150);
            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
            doc.text(
                'Sahakar Accounts System - Confidential',
                data.settings.margin.left,
                pageHeight - 10
            );
        },
    });

    doc.save(`${title.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

export const exportToExcel = (
    title: string,
    data: any[],
    metadata: ExportMetadata
) => {
    // Flatten data and add metadata as first rows
    const wsData = [
        ['SAHAKAR ACCOUNTS SYSTEM - CONFIDENTIAL'],
        [`Report: ${title}`],
        [`Generated by: ${metadata.user_name} (${metadata.user_role})`],
        [`Date: ${format(new Date(), 'dd MMM yyyy HH:mm')}`],
        [''], // Empty row
    ];

    // Add headers and data from input
    // Note: 'data' assumes array of objects. We need to convert to array of arrays or just use json_to_sheet
    // For better control, we'll append the data.

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(wsData);

    // Append actual data
    XLSX.utils.sheet_add_json(ws, data, { origin: 'A6' });

    // Column widths
    const wscols = [
        { wch: 20 },
        { wch: 20 },
        { wch: 20 },
        { wch: 20 },
        { wch: 30 },
    ];
    ws['!cols'] = wscols;

    XLSX.utils.book_append_sheet(wb, ws, 'Report');
    XLSX.writeFile(wb, `${title.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.xlsx`);
};
